spring.application.name=trading-platform
server.port=8081

# DATABASE CONNECTION AND JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/trading
spring.datasource.username=postgres
spring.datasource.password=9852
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=fdjksnfsd98fnsdfnsd89fnsdfnsd89fnsdf
jwt.expiration=3600000